config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :pages
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, PhotoUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> {order(:created_at => :desc)}
  has_many :comments, -> {order(:created_at => :desc)}
  has_many :bookmarks, -> {order(:created_at => :desc)}

  def is_liked user
    Like.find_by(user_id: user.id, post_id: id)
  end

  def is_bookmarked user
    Bookmark.find_by(user_id: user.id, post_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :bookmarks

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[github]
         
  validates :name, presence: true, length: {maximum: 50}

  def self.from_omniauth(auth)
    puts auth.info.email
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      # user.password = Devise.friendly_token[0,20]
      user.provider = auth.provider
      user.uid = auth.uid
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
    new(session["devise.user_attributes"]) do |user|
      user.attributes = params
      user.valid?
    end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  # def self.search(term)
  #   if term
  #     where('username LIKE ?', "%#{term}")
  #   else
  #     nil
  #   end
  # end

  private

  def adjust_email
    self.email = "fake+#{generate_token}" if email.blank?
    true
  end

  def generate_token
    rand(36**8).to_s(36).concat(“@gmail.com”)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :website, :bio])
  end
  
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :authenticate_user!

  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)
    @post = @bookmark.post
    @is_bookmarked = @bookmark
    if @bookmark.save
      respond_to :js
    else
      flash[:alert] = "Something went wrong.."
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @post = @bookmark.post
    if @bookmark.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong.."
    end
  end 

  private

  def bookmark_params
    params.permit :post_id, :user_id
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @comments = @post.comments.includes(:user)
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      @post = @comment.post
      respond_to :js
    else 
      flash[:alert] = "Something went wrong.."
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong.."
    end
  end

  private

  def comment_params
    params.required(:comment).permit :user_id, :post_id, :content
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    else
      flash[:alert] = "Something went wrong.."
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong.."
    end
  end 

  private

  def like_params
    params.permit :post_id
  end

end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  skip_before_action :verify_authenticity_token

  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_post, only: [:show, :destroy]
  
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 5).includes(:photos, :user, :likes, :bookmarks).order('created_at desc')
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      if params[:images]
        params[:images].each_key do |img|
          @post.photos.create(image: params[:images][img])
        end
      end
      redirect_to root_path, success: "Saved.."
    else
      redirect_to root_path, danger: "Something went wrong.."
    end
  end

  def show
    @photos = @post.photos
    @likes = @post.likes.includes(:user)
    @bookmarks = @post.bookmarks.includes(:user)
    @comment = Comment.new
    @is_liked = @post.is_liked(current_user)
    @is_bookmarked = @post.is_bookmarked(current_user)
  end


  def destroy
    if @post.user == current_user
      if @post.destroy
        flash[:notice] = "Post deleted!"
      else
        flash[:alert] = "Something went wrong.."
      end
    else
      flash[:notice] = "You don't have permission to do that!"
    end
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find_by id: params[:id]

    return if @post
    flash[:danger] = "Post not exists!"
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit(
      :content,
      :images
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.search(params[:term])
    respond_to :js
  end

  def show
    @user=User.find(params[:id])
    @posts = @user.posts.includes(:photos, :likes, :comments)
    @saved = Post.joins(:bookmarks).where(bookmarks: {user_id: current_user.id}).includes(:photos, :likes, :comments)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    {
      success: "alert-success",
      error: "alert-danger",
      danger: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }[name.to_sym] || name
  end

  def avatar_url user
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/create.js.erb
$('#bookmark-icon-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/bookmark_icon", {is_bookmarked: @is_bookmarked, post: @post} %>');
console.log('create bookmark success');

app/views/bookmarks/destroy.js.erb
$('#bookmark-icon-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/bookmark_icon", {is_bookmarked: @is_bookmarked, post: @post} %>');
console.log('cancel bookmark success');

app/views/comments/create.js.erb
$('#comment-post-<%= @post.id.to_s %>').
	html('<%= j render "posts/comment_list", {post: @post} %>');
$('#comment-form-post-<%= @post.id.to_s %> #comment_content').val("");
console.log("create comment success");

app/views/comments/destroy.js.erb
$('#comment-post-<%= @post.id.to_s %>').
	html('<%= j render "posts/comment_list", {post: @post} %>');
console.log("delete comment success");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagramm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>  
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <script src="https://kit.fontawesome.com/a934496ad3.js" crossorigin="anonymous"></script>


  <body>
    <%= render 'shared/navbar' if current_user %>
    <div class="container">
      <div class="row notifications">
      <div class = "col-md-12">
        <% flash.each do |name, message|%>
          <div class = "alert <%= bootstrap_class_for(name) %> alert-dismissible fade show" >
            <%= message %>
          </div>
         <% end %>          
        </div>
      </div>


      <div class="content">
        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to image_pack_tag("posts/heart_filled_red.svg", class: "post-heart-icon"), like_path(@like), method: :delete, remote: true, data: {confirm: "Are you shure to cancel like?"} %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", {likes: @post.likes} %>');
console.log('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!create like success');

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to image_pack_tag("posts/heart.svg", class: "post-heart-icon"), post_likes_path(@post), method: :post, remote: true %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", {likes: @post.likes} %>');
console.log('cancel like success!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!');

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_bookmark_icon.html.erb
<% if is_bookmarked.present? %>
	<%= link_to  image_pack_tag('posts/bookmark_filled.svg', class: 'post-bookmark-icon'), bookmark_path(is_bookmarked), method: :delete, remote: true, data: {confirm: "Are you shure to cancel bookmark?"} %>
<% else %>
	<%= link_to image_pack_tag('posts/bookmark.svg', class: 'post-bookmark-icon'), post_bookmarks_path(post), class: "col-sm-1", method: :post, remote: true %>
<% end %>

app/views/posts/_comment_form.html.erb
<%= form_for [post, Comment.new], :html => {:class => "w-100"}, remote: true do |f| %>
	<%= f.hidden_field :user_id, value: current_user.id.to_s %>
	<%= f.hidden_field :post_id, value: post.id %>
	<%= f.text_field :content, class: "form-control comment-input border-0", placeholder: "Add a comment ...", autocomplete: :off %>
<% end %>	

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
	<div class="mb-2">
		<div class="col-sm-10">
			<span>
				<strong>
					<%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration normal-color" %>
				</strong>
			</span>
			<span class="simply-text"><%= comment.content %></span>
		</div>
		<div class="col-sm-2">
			<% if comment.user == current_user%>
				<%= link_to comment_path(comment), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto delete-comment", data: {confirm: "You really want to delete comment?"}, remote: true do %>
					<i class="far fa-trash-alt" aria-hidden="true"></i>
				<% end%>
			<% end %>
		</div>
	</div>
<% end %>

app/views/posts/_like_icon.html.erb
<% if is_liked.present? %>
	<%= link_to  image_pack_tag('posts/heart_filled_red.svg', class: 'post-heart-icon'), like_path(is_liked), method: :delete, remote: true, data: {confirm: "Are you shure to cancel like?"} %>
<% else %>
	<%= link_to image_pack_tag('posts/heart.svg', class: 'post-heart-icon'), post_likes_path(post), class: "col-sm-1", method: :post, remote: true %>
<% end %>

app/views/posts/_like_text.html.erb
<% likes.each_with_index do |like, index| %>
<strong>
	<% if likes.size == 1 %>
		<%= like.user.name %> </strong> 
		<span class="simply-text">
			like this
		</span>
	<% elsif like == likes.last %>
		</strong> 
		<span class="simply-text">
			and
		</span>
		<strong>
		<%= + like.user.name %></strong> 
		<span class="simply-text">
			like this
		</span>
	<% elsif index > 1 %>
		</strong>
		<span class="simply-text">
		<%= "and" + (likes.size-index).to_s + "others" %> 
			like this
		</span>
		<% break %>
	<% elsif index == likes.size-2 || index == 1 %>
		<%=  like.user.name %>
	<% else %>
		<%= like.user.name + ", "%>
	<% end %>
<% end %>

app/views/posts/_photos.html.erb
<%= link_to post_path(post) do %>
	<% if post.photos.any? %>
		<div id="carouselExampleFade-<%= post.id %>" class="carousel slide carousel-fade" data-bs-ride="carousel">
			<div class="carousel-inner">
			  	<% post.photos.each_with_index do |photo, ind| %>
					<% if photo.image.url(:standard) != nil %>
					<div class="carousel-item <%= "active" if  ind == 0 %>">
						<%= image_tag photo.image.url(:standard), class: "block w-100"%>
					</div>
					<% end %>
				<% end %>
			</div>
			<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade-<%= post.id %>" data-bs-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		    	<span class="visually-hidden">Previous</span>
			</button>
		  	<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade-<%= post.id %>" data-bs-slide="next">
		    	<span class="carousel-control-next-icon" aria-hidden="true"></span>
		    	<span class="visually-hidden">Next</span>
		  	</button>
		</div>
	<% end %>
<% end %>

app/views/posts/_posts_list.html.erb
<% @posts.each do |post| %>
	<div class="card mt-3 post">
		<div class="card-header d-flex align-items-center">
			<div class="col-sm-11">
				<%= link_to user_path(post.user), class: "no-text-decoration" do %>
					<%= image_tag avatar_url(post.user), class: "post-author-icon"%>
				<% end %>
				<%= link_to user_path(post.user), class: "normal-color no-text-decoration", title: post.user.name do %>
					<strong><%= post.user.name %></strong>
				<% end %>
			</div>
			<% if post.user == current_user %>
				<div class="col-sm-1">
					<%= link_to post_path(post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto text-right", data: {confirm: "You really wants to delete post?"} do %>
						<i class="far fa-trash-alt" aria-hidden="true"></i>
					<% end%>
				</div>
			<% end %>
		</div>

		<%= render "photos", {post: post} %>

		<div class="card-body">
			<div class="row actions">
				<div id="like-icon-post-<%= post.id.to_s %>" class= "col-sm-1">
					<%= render "like_icon", {is_liked: post.is_liked(current_user), post: post} %>
				</div>
				<div class="col-sm-1">				
					<%= link_to image_pack_tag('posts/comment.svg', class: 'post-comment-icon'), '#' %>
				</div>
				<div class="col-sm-9"></div>


				<div id="bookmark-icon-post-<%= post.id.to_s %>" class= "col-sm-1">
					<%= render "bookmark_icon", {is_bookmarked: post.is_bookmarked(current_user), post: post} %>
				</div>

			</div>

			<div id="like-text-post-<%= post.id.to_s %>">
				<%= render "like_text", {likes: post.likes} %>
			</div>	
			
			<div>
				<span>
					<strong><%= post.user.name %></strong>
					<span class="simply-text"><%= post.content %></span>
				</span>
			</div>

			<div id="comment-post-<%= post.id.to_s %>">
				<%= render "comment_list", {post: post} %>
			</div>

			<%= link_to time_ago_in_words(post.created_at).upcase + "AGO", post_path(post), class: "light-color post-time no-text-decoration" %>
			<hr>
			<div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
				<%= render "comment_form", {post: post} %>
			</div>
		</div>
	</div>
<% end %>

app/views/posts/index.html.erb
<div class="d-flex flex-column align-items-center mt-3">
	<div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
		<div class="card">
			<div class="card-header">
				Create Post
			</div>
			<div class="card-body">
				<%= form_for @post, :html => {:multipart => true, :class => "dropzone upload-images p-0 border-0"} do |f| %>
					<div class="form-group row mt-2">
						<div class="col-auto pr-0">
							<%= image_tag avatar_url(current_user), class: "post-author-icon"%>
						</div>
						<div class="col pl-0">
							<%= f.text_field :content, class: "form-control border-0", placeholder: "Say smth about this" %>
						</div>
					</div>
					<div class="fallback">
						<%= file_field_tag "images[]", type: :file, multiple: true %>
					</div>
					<div class="dz-message m-0"></div>
					<div class="dropzone-previews mb-3">
						<div class="upload-photos-icon">
							<i class="fa fa-plus fa-2x" aria-hidden = "true" style = "color: #dddfe2"></i>
						</div>
					</div>
					<%= f.submit "Post", class: "btn btn-outline-secondary" %>
				<% end %>
			</div>
		</div>
		<div id="posts">
			<%= render 'posts_list' %>
		</div>
	</div>
	<div>
		<br>
	</div>
	<br>
	<%= will_paginate @posts %>
</div>


app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center mt-3">
	<div class="row post box col-xl-10 col-lg-11 col-xs-12">
		<div class="col-lg-8 col-md-7 px-0 d-flex post-show-img">
			<div class="align-self-center">
				<%= render "photos", {post: @post} %>
			</div>
		</div>
		<div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0">			
			<div class="row px-3 d-flex align-items-center">
				<div class="col-sm-3">
					<%= link_to user_path(@post.user), class: "no-text-decoration" do%>
						<%= image_tag avatar_url(@post.user), class: "post-author-icon" %>
					<% end %>
				<div class="col-sm-8">
					<%= link_to user_path(@post.user), class: "normal-color no-text-decoration d-flex align-self-center", title: @post.user.name do %>
						<strong><%= @post.user.name %></strong>
					<% end %>
				</div>
				<% if @post.user == current_user %>
					<div class="col-sm-1">
						<%= link_to post_path(@post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto", data: {confirm: "You really wants to delete post?"} do %>
							<i class="far fa-trash-alt" aria-hidden="true"></i>
						<% end%>
					</div>
				<% end %>
			</div>
			<hr class="mb-0">
			<div class="comment-list py-2">
				<% if @post.content.present? %>
					<div>
						<span>
							<strong><%= @post.user.name %></strong>
						</span>
						<span>
							<%= @post.content %>
						</span>
					</div>
				<% end %>
				
				<div id="comment-post-<%= @post.id.to_s %>">
					<%= render "comment_list", {post: @post} %>
				</div>
			</div>
			
			<hr class="mt-0">
			<div>
				<div class="row actions">
					<div id="like-icon-post-<%= @post.id.to_s %>" class= "col-sm-2">
						<%= render "like_icon", {is_liked: @is_liked, post: @post} %>
					</div>
					<%= link_to image_pack_tag('posts/comment.svg', class: 'post-comment-icon'), '#', class: "col-sm-1"%>
					<div class="col-sm-7"></div>

					<div id="bookmark-icon-post-<%= @post.id.to_s %>" class= "col-sm-1">
						<%= render "bookmark_icon", {is_bookmarked: @is_bookmarked, post: @post} %>
					</div>

				</div>
				<div id="like-text-post-<%= @post.id.to_s %>">
					<%= render "like_text", {likes: @likes} %>
				</div>		
			</div>	
			<%= link_to time_ago_in_words(@post.created_at).upcase + "AGO", post_path(@post), class: "light-color post-time no-text-decoration" %>
			<hr>
			<div class="row actions" id="comment-form-post-<%= @post.id %>">
				<%= render "comment_form", {post: @post} %>
			</div>
		</div>
	</div>
</div> 

app/views/shared/_footer.html.erb
<footer class= "footer">
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<button class="navbar-toggler" type= "button" data-toggle = "collapse" data-target="#navbar">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapsse navbar-collapse" id="navbar">
			<div class="navbar-nav mx-auto">
				<%= link_to 'ABOUT US', '#', class: "nav-item nav-link" %>
				<%= link_to 'SUPPORT', '#', class: "nav-item nav-link" %>
				<%= link_to 'BLOG', '#', class: "nav-item nav-link" %>
				<%= link_to 'PRESS', '#', class: "nav-item nav-link" %>
				<%= link_to 'API', '#', class: "nav-item nav-link" %>
				<%= link_to 'JOB', '#', class: "nav-item nav-link" %>
				<%= link_to 'PRIVACY', '#', class: "nav-item nav-link" %>
				<%= link_to 'TERMS', '#', class: "nav-item nav-link" %>
				<%= link_to 'DIRECTORY', '#', class: "nav-item nav-link" %>
				<%= link_to 'LANGUAGE', '#', class: "nav-item nav-link" %>
			</div>				
		</div>
	</nav>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <div class="container">
    <%= link_to image_pack_tag('core-sprite-2x.png', class: 'main-img'), root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

<!--     <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      <form class="d-flex">
        <input class="form-control me-2 justify-content-end" type="search" placeholder="Search" aria-label="Search">
      </form>
    </div> -->
    <div>
      <ul class="navbar-nav justify-content-end">

        <li class="nav-item">
          <%= link_to image_pack_tag('search.svg', class: 'explore-icon'), '#', class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to image_pack_tag('heart.svg', class: 'notification-icon'), '#', class: "nav-link"%>
        </li>
        <li class="nav-item profile-icon">
          <%= link_to image_pack_tag('person.svg', class: 'profile-icon'), user_path(current_user), class: "nav-link"%>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'sign out', destroy_user_session_path, method: :delete, class: "nav-link btn btn-outline-secondary"%>
          </li>
          <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/users/_post.html.erb
<% posts.each do |post| %>
	<div class="col-sm-4">
		<%= link_to post_path(post) do %>
			<div class="post-stat d-flex justify-content-center align-items-center">
				<span>
					<i class="fa fa-heart" aria-hidden="true"></i>
					<%= post.likes.size %>
					<span></span>
					<i class="ml-3 fa fa-comment" aria-hidden="true"></i>
					<%= post.comments.size %>
				</span>
			</div>
			<%= image_tag post.photos.first.image.url(:standard), class: "card-img-top image-preview" %>
		<% end %>
	</div>
<% end %>

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
	<div class="col-md-4 text-center">
		<!-- stub for image -->
		<%= image_tag avatar_url(@user), class: "user-image" %>
	</div>

	<div class="col-md-8 text-center">
		<div class="row">
			<p class="username">
				<%= @user.name %>
			</p>
			<div>
				<br>
			</div>
			<% if @user == current_user %>
				<%= link_to 'Edit profile', edit_user_registration_path , class: "btn btn-outline-secondary edit-profile" %>
				<br>
				<div>
					<br>
				</div>
				<button type="button" class="btn btn-outline-secondary edit-profile settings" data-bs-toggle="modal" data-bs-target="#exampleModal">
					Settings
				</button>
				
				<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
					<div class="modal-dialog modal-dialog-centered">
					    <div class="modal-content">
						    <div class="modal-header">
						    	<h5 class="modal-title" id="exampleModalLabel">Settings</h5>
						    	<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						    </div>
						    <div class="list-group text-center">
						    	<%= link_to 'Change password', '#', class: "list-group list-group-item-action btn btn-outline-secondary"%>
						    	<%= link_to 'sign out', destroy_user_session_path, method: :delete, class: "list-group list-group-item-action btn btn-outline-warning"%>
						    	<button class="list-group list-group-item-action btn btn-outline-danger" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
						    </div>
					    </div>
					</div>
				</div>
			<% end %>
		</div>
		<div>
			<br>
		</div>
		<div class="row">
			<p class="email">
				<%= @user.email %>
			</p>
		</div>
		<% if @user == current_user %>
			<div class="row account-created">
				<p>
					Account created at <%= @user.created_at.to_date.strftime("%d %B %Y") %>
				</p>
				<p>
					Updated at <%= @user.updated_at.to_date.strftime("%d %B %Y") %>
				</p>
			</div>
		<% end %>
	</div>
	<div class="profile-tab">
		<% if @user == current_user %>
			<nav>
				<div class="nav nav-tabs d-flex justify-content-center" id="nav-tab" role="tablist">
				    <button class="nav-link active" id="nav-post-tab" data-bs-toggle="tab" data-bs-target="#nav-post" type="button" role="tab" aria-controls="nav-post" aria-selected="true">POSTS</button>
				    <button class="nav-link" id="nav-saved-tab" data-bs-toggle="tab" data-bs-target="#nav-saved" type="button" role="tab" aria-controls="nav-saved" aria-selected="false">SAVED</button>
				</div>
			</nav>
		<% end %>
		<div class="tab-content pb-3" id="nav-tabContent">
			<div class="tab-pane fade show active" id="nav-post" role="tabpanel" aria-labelledby="nav-post-tab">
				<div class="row">
					<%= render "post", {posts: @posts} %>
				</div>
			</div>
			<div class="tab-pane fade" id="nav-saved" role="tabpanel" aria-labelledby="nav-saved-tab">
				<div class="row">
					<%= render "post", {posts: @saved} if @user == current_user %>
				</div>
			</div>
		</div>
	</div>
	

</div>